- id: buildifier
  name: buildifier
  description: Format starlark code with buildifier
  entry: buildifier-wrapper.sh
  args: [-mode=fix, -lint=fix]
  files: '^(.*/)?(BUILD\.bazel|BUILD|WORKSPACE)$|\.BUILD$|\.bzl$'
  language: script
- id: buildifier-lint
  name: buildifier-lint
  description: Lint starlark code with buildifier
  entry: buildifier-wrapper.sh
  args: [-mode=diff, -lint=warn]
  files: '^(.*/)?(BUILD\.bazel|BUILD|WORKSPACE)$|\.BUILD$|\.bzl$'
  language: script
